// AUTO-GENERATED by scripts/gen-memory-layout.js. DO NOT EDIT.
#pragma once

namespace moonvst::memory_layout {
static constexpr int BYTES_PER_SAMPLE = 4;
static constexpr int INPUT_LEFT_OFFSET = 0x10000;
static constexpr int INPUT_RIGHT_OFFSET = 0x20000;
static constexpr int OUTPUT_LEFT_OFFSET = 0x30000;
static constexpr int OUTPUT_RIGHT_OFFSET = 0x40000;
static constexpr int STRING_BUF_OFFSET = 0x50000;
static constexpr int REVERB_MEM_BASE_PTR = 0x60000;
static constexpr int CHORUS_MEM_BASE_PTR = 0x78000;
static constexpr int MAX_BUFFER_SAMPLES = 16384;
}
